version: "3.9"

services:
  dev:
    build:
      context: ..
      dockerfile: docker/dev.Dockerfile
    container_name: dotnet-dev-env
    volumes:
      - ../:/workspace
    command: sleep infinity
    tty: true

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: dev-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Strong!Pass123"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
